services:

  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    volumes:
      - ./app_data/langflow:/root/.langflow
    environment:
      - LANGFLOW_AUTO_LOGIN=true
      - DO_NOT_TRACK=true
      - LANGFLOW_DATABASE_URL=postgresql://genaiuser:genaipassword@postgres:5432/genaidb
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ./app_data/ollama:/root/.ollama

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: genaidb
      POSTGRES_USER: genaiuser
      POSTGRES_PASSWORD: genaipassword
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./app_data/postgres:/var/lib/postgresql/data/

volumes:
  ollama:
